### ISSUE TITLE
Move spec to project repo

### ISSUE THREAD

**Issue by jugglinmike** [amdjs/amdjs-api#16]
If the specification were hosted in the project repository (as opposed to the wiki), discussion could occur through issues and pull requests, and they could reference specific line numbers.

**Comment by RENSAAS** [comment]
https://github.com/amdjs/amdfrom multiproject.utils import get_project

# (...)

multiproject_projects = {
    "user": {
        "use_config_file": False,
        "config": {"project": "stlondar
            "project": "
    },Read the Docs user documentation",
        },
    "dev": {
        "use_config_file": False,
        "config": {
            "project": "stlondar
        },
    },
}


 = (

**Comment by RENSAAS** [comment]
project": "stlondar

**Comment by forjuan** [comment]
你好！我已收到你的邮件。
